# Customise this file, documentation can be found here:
# https://docs.fastlane.tools/actions/
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.98.0"

default_platform :ios

platform :ios do
  $lane_active = ""
  before_all do
    skip_docs
  end

  desc "Runs all the tests"
  lane :test do
    $lane_active = "Test"
    scan(
      project: ENV["XCODE_PROJECT"],
      scheme: ENV["XCODE_SCHEME"],
      clean: true,
      code_coverage: true
    )
  end

  desc "Run code coverage with xcov"
  lane :coverage do
    $lane_active = "Coverage"
    xcov(
      project: ENV["XCODE_PROJECT"],
      scheme: ENV["XCODE_SCHEME"],
      output_directory: "coverage",
      html_report: false,
      json_report: true,
      only_project_targets: true
    )
    xcov_report    
  end

  desc "Submit a new demo Build to Apple TestFlight"
  lane :demo do
    $lane_active = "Demo"
    # Fetch provisioning profile
    # sigh
    sigh(
      adhoc: false
    )
  
    # Build
    gym(
      # app_identifier: "org.glpi-project.api-client-demo",
      workspace: "Glpi.xcworkspace",#ENV["XCODE_WORKSPACE_DEMO"]
      scheme: "Example",#ENV["XCODE_SCHEME_DEMO"],
      configuration: "Release",
      sdk: "iphoneos11.0",
      clean: true,
      include_bitcode: true,
      include_symbols: true,
      export_method: "app-store",
      buildlog_path: 'fastlane/logs'
    )

    # TestFlight upload
    pilot(
      app_identifier: "org.glpi-project.api-client-demo",#ENV["APP_IDENTIFIER"],
      skip_waiting_for_build_processing: true
    )
  end

  after_all do |lane|
    telegram(
        url_horn: ENV["TELEGRAM_WEBHOOKS"],
        message: $lane_active + " Fastlane is OK"
    )
  end

  error do |lane, exception|
    telegram(
        url_horn: ENV["TELEGRAM_WEBHOOKS"],
        message: "`ERROR` " + $lane_active + " Fastlane FAIL"
    )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded. 
# Learn more at https://github.com/fastlane/fastlane#metrics
